name: "Deploy images to GitHub Pages"

on:
  push:
    tags:
      - "img-v*"

jobs:
  build:
    name: "Deploy"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Git repository
        uses: "actions/checkout@v2"

      - name: "Deploy"
        uses: "peaceiris/actions-gh-pages@v3"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: "deploy"
          publish_dir: "./image"